/*
 * Remote Examination Api
 *
 * Remote Examination Support management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: davidtruhlarac@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_ufe

import (
	"github.com/gin-gonic/gin"
)

type AmbulanceRemoteConsultationAPI interface {


    // CreateConsultationEntry Post /api/remote-consultation/:ambulanceId/entries
    // Creates new consultation entry 
     CreateConsultationEntry(c *gin.Context)

    // DeleteConsultationEntry Delete /api/remote-consultation/:ambulanceId/entries/:entryId
    // Deletes a consultation entry 
     DeleteConsultationEntry(c *gin.Context)

    // GetConsultationEntries Get /api/remote-consultation/:ambulanceId/entries
    // Provides list of active remote consultation cases 
     GetConsultationEntries(c *gin.Context)

    // GetConsultationEntry Get /api/remote-consultation/:ambulanceId/entries/:entryId
    // Provides a single consultation entry 
     GetConsultationEntry(c *gin.Context)

    // GetConsultationProtocol Get /api/remote-consultation/:ambulanceId/entries/:entryId/protocol
    // Provides the communication protocol for a consultation 
     GetConsultationProtocol(c *gin.Context)

    // UpdateConsultationEntry Put /api/remote-consultation/:ambulanceId/entries/:entryId
    // Updates a consultation entry 
     UpdateConsultationEntry(c *gin.Context)

    // UpdateConsultationProtocol Put /api/remote-consultation/:ambulanceId/entries/:entryId/protocol
    // Updates the communication protocol 
     UpdateConsultationProtocol(c *gin.Context)

}