/*
 * Remote Examination Api
 *
 * Remote Examination Support management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: davidtruhlarac@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_ufe

import (
	"time"
)

type ConsultationEntry struct {

	// Unique id of the consultation entry
	Id string `json:"id"`

	// Unique identifier of the patient
	PatientId string `json:"patientId"`

	// Full name of the patient
	PatientName string `json:"patientName"`

	// Primary condition or reason for consultation
	Condition string `json:"condition,omitempty"`

	// Current status of the consultation
	Status string `json:"status"`

	// Timestamp when the consultation was created
	CreatedAt time.Time `json:"createdAt"`
}
