/*
 * Remote Examination Api
 *
 * Remote Examination Support management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: davidtruhlarac@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_ufe

import (
	"time"
)

type CommunicationProtocol struct {

	// Unique id of the protocol
	Id string `json:"id"`

	// Reference to the consultation entry
	EntryId string `json:"entryId"`

	// Content of the communication protocol
	Content string `json:"content"`

	// Current status of the protocol
	Status string `json:"status"`

	// Timestamp of last update
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
